---
# Tasks for webserver role
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /tmp/nginx.conf
    mode: '0644'
  notify: Restart Nginx

- name: Create web content directory
  ansible.builtin.file:
    path: /tmp/www
    state: directory
    mode: '0755'

- name: Create test HTML file
  ansible.builtin.template:
    src: index.html.j2
    dest: /tmp/www/index.html
    mode: '0644'
