---
# Tasks for database role
- name: Install SQLite
  ansible.builtin.package:
    name: sqlite3
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Create database directory
  ansible.builtin.file:
    path: /tmp/db
    state: directory
    mode: '0755'

- name: Create test database
  ansible.builtin.copy:
    content: ""
    dest: /tmp/db/test.db
    force: no
    mode: '0644'

- name: Initialize database schema
  ansible.builtin.template:
    src: schema.sql.j2
    dest: /tmp/db/schema.sql
    mode: '0644'

- name: Apply database schema
  ansible.builtin.shell: |
    sqlite3 /tmp/db/test.db < /tmp/db/schema.sql
  args:
    creates: /tmp/db/.initialized
  register: db_init

- name: Mark database as initialized
  ansible.builtin.file:
    path: /tmp/db/.initialized
    state: touch
    mode: '0644'
  when: db_init.changed
